### ISSUE TITLE
PHP <= 7.4 Support

### ISSUE THREAD

**Issue by nadinengland** [izi-dev/nova-key-value-suggestion-field#1]
Love the idea of this package! However, I'm unable to use it on pre-PHP 7.4 sites as it is using typed properties: https://github.com/izi-dev/nova-key-value-suggestion-field/blob/master/src/KeyValueSuggestion.php#L20

Any chance you can remove this so earlier PHP versions can be supported?

**Comment by izi-dev** [comment]
Sure, I'm new to this, excuse me, I already ruined it.

**Comment by izi-dev** [comment]
@nadinengland ready, check version 1.0.1

**Comment by nadinengland** [comment]
Brilliant thank you @izi-dev
